# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Automate Environment Deployment Approval"
description: "Automatically approve a deployment to Github environment"
branding:
  # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
  icon: "check-circle"
  color: "orange"
author: "@activescott"
inputs:
  environment_allow_list:
    required: true
    description: The list of environments to automatically approve deploys for. Can be a newline-delimited list of strings.
  actor_allow_list:
    required: true
    description: The list of users to automatically approve deploys for. Can be a newline-delimited list of strings.

runs:
  using: "node16"
  main: "dist/index.js"
