on:
  # when a PR is labeled we'll trigger this (dependabot always labels its PRs)
  pull_request_target:
    types: [labeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    # Specifically check that dependabot (or another trusted party) created this pull-request, and that it has been labelled correctly.
    if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - uses: alexwilson/enable-github-automerge-action@6c135e46075c098c5e52de011bb8cab4522fec3f
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
