name: Label PR w/ auto-merge status
on:
  pull_request_target:
    types: [auto_merge_enabled, auto_merge_disabled]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    uses: activescott/github-actions-workflows/.github/workflows/pr-auto-merge-labeler.yml@pr-auto-merge-labeler-v1
